name: Build
on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]

jobs:
  get-version:
    name: Version
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2.3.4
      with:
        # Fetch all branches and tags to determine semantic version
        fetch-depth: 0

    - name: 'Release: Extract branch name'
      run: echo "##[set-output name=branch-name;]${GITHUB_REF##*/}"
      id: extract-branch

    - name: Calculate Version
      id: version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        short_tags: false
        format: "${major}.${minor}.${patch}-${{ steps.extract-branch.outputs.branch-name }}.${increment}"

    - name: Create Artifact
      # You may pin to the exact commit or the version.
      uses: 1arp/create-a-file-action@0.2
      with:
        file: ${{ steps.version.outputs.version }}.txt
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ steps.version.outputs.version }}
        path: '**/*.txt'
        if-no-files-found: error

    - name: 'Release Candidate: Print shortcut to create release'
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
      run: echo "::warning::URL to create..."
